-- prompt_templates 种子数据（UPSERT，本地+生产通用）
-- 用法: mysql -uroot -p<password> --default-character-set=utf8mb4 ai_anime < seed-prompt-templates.sql
-- 2026-08-12: 生产库该表为空导致「剧本AI分析」报『系统未配置剧本分析模板』（drama.service.ts analyze 按 name='剧本分析模板' 查找）。
-- 2026-08-13: 两阶段分析改造——模板 1 收敛为「结构分析」模板（标题/风格/每集概述/全局资产清单），
--       新增模板 7「剧本分段扩展模板」逐集扩展片段，支持大集数（6-24 集）不再受单次 8192 tokens 输出上限限制。
SET NAMES utf8mb4;

INSERT INTO `prompt_templates` (`id`,`name`,`provider`,`capability`,`template`,`variables`,`description`,`status`,`created_at`,`updated_at`) VALUES
(1,'剧本分析模板',NULL,NULL,'你是一位专业的短剧剧本分析专家。请分析以下剧本大纲，输出短剧整体结构（标题/风格/每集概述/全局资产清单）。后续阶段会根据每集概述逐集扩展视频片段，因此本阶段只输出结构，不要输出片段。\n\n剧本大纲：\n{{outline}}\n\n语言规则：prompt 字段必须用英文；其余所有文本字段（title/genre/targetAudience/summary/name/role/description）一律使用中文，与剧本大纲语言一致。\n\n请输出以下 JSON(所有字段必填):\n{\n  title: 剧名(中文),\n  genre: 类型/题材(中文),\n  targetAudience: 目标受众(中文),\n  style: 风格(anime/realistic),\n  episodeCount: 集数,\n  episodes: [\n    {\n      episodeNo: 1,\n      title: 第1集标题(中文),\n      summary: 本集剧情概述(中文,简洁,50字以内),\n      duration: 60\n    }\n  ],\n  assets: {\n    characters: [\n      {\n        name: 角色名(中文),\n        role: 角色定位(主角/配角/反派,中文),\n        description: 角色外貌特征描述(中文,精简),\n        prompt: 英文图像生成提示词,\n        prompt_cn: 中文翻译\n      }\n    ],\n    props: [\n      {\n        name: 道具名(中文),\n        description: 道具外观描述(中文,精简),\n        prompt: 英文图像生成提示词,\n        prompt_cn: 中文翻译\n      }\n    ],\n    scenes: [\n      {\n        name: 场景名(中文),\n        description: 场景环境描述(中文,精简),\n        prompt: 英文图像生成提示词,\n        prompt_cn: 中文翻译\n      }\n    ]\n  }\n}\n\n输出要求(严格控制篇幅，否则输出会被截断):\n1. 剧集数量必须等于目标集数 {{episodeCount}}（6-24 集）\n2. 每集只输出 episodeNo/title/summary/duration，不要输出 segments（片段在后续阶段生成）\n3. 所有片段会用到的角色/道具/场景必须在此 assets 中定义齐全\n4. assets 中角色不超过 8 个、道具不超过 6 个、场景不超过 6 个,描述精简\n5. 每个 prompt 不超过 30 个英文单词, prompt_cn 不超过 50 个汉字\n6. 除 prompt 外所有文本字段必须使用中文\n7. 只输出 JSON,不要包含任何其他文字','outline, episodeCount','分析剧本大纲输出短剧结构（两阶段分析·阶段1）','active','2026-07-14 17:58:38.119684','2026-08-13 00:00:00.000000'),
(7,'剧本分段扩展模板',NULL,'script','你是短剧片段拆分专家。根据单集剧情概述，将该集拆分为 1-2 个连贯的视频片段。\n\n本集信息：\n{{episodeInfo}}\n\n全局角色/道具/场景清单（片段中只能引用清单中已定义的名字）：\n{{globalAssets}}\n\n语言规则：prompt 字段必须用英文；其余所有文本字段（episodeNo/title/summary/characters/props/scenes）一律使用中文，与本集信息一致。\n\n请输出如下 JSON(所有字段必填):\n{\n  episodeNo: 本集集号,\n  title: 本集标题(中文),\n  segments: [\n    {\n      segmentNo: 1,\n      summary: 片段内容概述(中文,简洁),\n      prompt: 英文视频生成提示词(包含人物动作/场景/镜头语言, 供 AI 生成视频),\n      prompt_cn: 中文翻译(供中文模型使用),\n      characters: [角色名(中文)],\n      props: [道具名(中文)],\n      scenes: [场景名(中文)],\n      duration: 5\n    }\n  ]\n}\n\n输出要求(严格控制篇幅):\n1. 片段数量 1-2 个，每个片段时长 5-10 秒\n2. 每个 prompt 不超过 30 个英文单词, prompt_cn 不超过 50 个汉字\n3. characters/props/scenes 只能引用全局清单中已定义的名字，没有相关项则不填\n4. 除 prompt 外所有文本字段必须使用中文\n5. prompt 必须纯英文，禁止出现任何中文字符（涉及角色/道具/场景时用英文表达，如 dark green canvas bag）\n6. 只输出 JSON,不要包含任何其他文字','episodeInfo, globalAssets','两阶段分析·阶段2：按单集概述扩展视频片段','active','2026-07-14 17:58:38.119684','2026-08-13 00:00:00.000000'),
(2,'资产生成提示词增强',NULL,'image','你是一位专业的资产生成提示词优化专家，请根据资产描述优化出高质量的 AI 生成提示词。\n\n资产描述：{{description}}\n风格：{{style}}\n资产类型：{{assetType}}\n\n要求:\n1. 补充视觉细节(如:角色/道具/场景的材质/颜色/光影/构图)\n2. 描述简洁具体,画面感强\n3. 只输出如下 JSON:\n{\n  "prompt": "英文提示词(供 AI 生图)",\n  "prompt_cn": "中文翻译(供中文模型使用)"\n}\n4. 若 style 为 realistic 时使用写实描述,anime 时使用动漫风格描述\n5. 中文 prompt_cn 需与英文 prompt 对应\n\n只输出 JSON,不要包含任何其他文字','description, style, assetType','优化资产生成的提示词质量','active','2026-07-14 17:58:38.119684','2026-08-12 00:00:00.000000'),
(3,'短剧片段提示词增强',NULL,'video','你是短剧视频片段提示词优化专家，请将以下片段信息优化为高质量 AI 视频生成提示词。\n\n片段描述：{{sceneDescription}}\n角色动作：{{characterAction}}\n参考素材：{{referenceDescription}}\n风格：{{style}}\n时长：{{duration}}秒\n\n要求:\n1. 补充画面细节、人物动作、镜头语言、氛围光线\n2. 合理控制节奏(快/慢/正常节奏)\n3. 保持人物形象一致\n4. 符合剧本叙事,突出剧情张力\n5. 画面构图合理\n6. 只输出如下 JSON:\n{\n  "prompt": "英文视频生成提示词(供 AI 模型使用)",\n  "prompt_cn": "中文翻译(供中文模型使用)"\n}\n\n只输出 JSON,不要包含任何其他文字','sceneDescription, characterAction, referenceDescription, style, duration','优化视频片段生成的提示词质量','active','2026-07-14 17:58:38.119684','2026-08-12 00:00:00.000000'),
(4,'通用提示词增强',NULL,NULL,'请优化以下AI 生成提示词，使其更详细、更具体、更适合生成高质量内容。\n\n原始提示词：{{prompt}}\n生成类型：{{type}}（image/video/audio）\n风格偏好：{{style}}\n\n优化原则：\n1. 补充视觉细节（光线、颜色、纹理、构图、视角）\n2. 加入风格关键词（{{style}}风格）\n3. 控制在 150-300 字\n4. 保留原始提示词的核心意图\n5. 添加正面质量标签（high quality, detailed, masterpiece 等）\n6. 如果知道输出分辨率，加入对应的构图建议\n7. 中英文混合效果更好\n\n只返回优化后的提示词','prompt, type, style','通用提示词增强，适用于任何生成类型','active','2026-07-14 17:58:38.119684','2026-08-12 00:00:00.000000'),
(6,'剧本智能拆分模板',NULL,'script','你是一个专业的剧本拆分专家。请分析以下剧本内容，将其拆分为合理的场景片段。\n\n剧本内容：\n{{content}}\n\n要求：\n1. 根据剧情发展、地点变化、时间转换来划分场景\n2. 每个场景应有完整的叙事单元\n3. 场景数量 3-10 个，每段 5-10 秒\n4. 为每个场景生成简短的视频生成提示词（prompt），描述画面和动作\n5. 提示词必须使用中文\n6. 确保场景之间的剧情连贯\n\n请以严格的 JSON 格式返回：\n{\n  scenes: [\n    {\n      index: 0,\n      prompt: "画面描述和动作提示词（用中文）",\n      duration: 5\n    }\n  ]\n}\n\n只返回 JSON，不要加任何其他文字说明','content','AI 智能分析剧本内容并拆分为合理的场景','active','2026-07-15 18:02:25.665837','2026-08-12 00:00:00.000000')
ON DUPLICATE KEY UPDATE
  `name` = VALUES(`name`),
  `provider` = VALUES(`provider`),
  `capability` = VALUES(`capability`),
  `template` = VALUES(`template`),
  `variables` = VALUES(`variables`),
  `description` = VALUES(`description`),
  `status` = VALUES(`status`),
  `updated_at` = VALUES(`updated_at`);
